### ISSUE TITLE
Update to JDK7

### ISSUE THREAD

**Issue by ewencp** [confluentinc/packaging#14]
This is a meta-issue for all the changes we need to make to update to JDK 7. Generally there are three high level things need to be changed: individual projects need to update pom files, individual package builds need to be converted to use jdk7, and VMs for packaging/system tests need to update their configurations.

- [x] Update pom in common https://github.com/confluentinc/common/pull/18
- [x] Update pom in rest-utils https://github.com/confluentinc/rest-utils/pull/19
- [x] Update pom in schema-registry https://github.com/confluentinc/schema-registry/pull/196
- [x] Update pom in kafka-rest https://github.com/confluentinc/kafka-rest/pull/99
- [x] Update pom in camus (manually pushed https://github.com/confluentinc/camus/commit/0b0962f3660f559f5f0cc3af0a8bbf2ae48cc43e after realizing we needed Java7 support immediately to not break downstream builds from common/rest-utils/schema-registry and update from upstream linkedin/camus would not arrive immediately)
- [x] Update pom in copycat https://github.com/confluentinc/copycat/pull/5
- [x] Update pom in copycat-hdfs https://github.com/confluentinc/copycat-hdfs/pull/5
- [x] Update pom in copycat-jdbc https://github.com/confluentinc/copycat-jdbc/pull/7
- [x] muckrake Vagrantfile & provisioning scripts https://github.com/confluentinc/muckrake/pull/35
- [x] Update kafka-packaging build branches
- [x] Update common build branches
- [x] Update rest-utils build branches
- [x] Update schema-registry build branches
- [x] Update kafka-rest build branches
- [x] Update camus build branches?
- [x] Update confluentinc/packaging scripts (Vagrant scripts, build + testing scripts) for JDK 7
- [x] confluentinc/infra is already moved to jdk7, but we could remove the remaining jdk6 remnants https://github.com/confluentinc/infra/pull/3
- [x] Does confluentinc/examples need updating? https://github.com/confluentinc/examples/pull/2

For individual packages, we should not have Depends clauses in the packages for Java because that causes problems if you want to use a non-system-provided JVM, so it should only be a build issue. If I remember correctly, only the RPMs actually specify Build-Depends. Everything else just relies on the VM being used to have the right thing installed, which should only require fixes in confluentinc/packaging.

I'm also going to add removing Scala 2.9 support to this ticket. This is being dropped in https://issues.apache.org/jira/browse/KAFKA-2348 and while they are not strictly related, the packaging scripts will probably need both changes to be made. Additionally, there have been some other changes in the meantime that are no longer 2.9 compatible, so the 2.9 builds are likely broken anyway and it would therefore be very difficult to fix the rest of this issue without removing 2.9

**Comment by ijuma** [comment]
I've done a bunch of trivial PRs. I had an initial look at `confluentinc/packaging`, but I think it needs someone more familiar with it (it's not clear if Java 7 needs to be uploaded to the S3 folder and other such things).

**Comment by ewencp** [comment]
@ijuma I merged the ones that aren't currently affected by automated tests and which I could manually verify. Once the muckrake patch is done, we can merge all the ones for projects that were part of CP 1.0.

The packaging stuff can happen afterward merging the other stuff. Right now I'm probably the only one familiar enough with it to make those changes, and I'll take care of them -- I just wanted it all to be listed here to make sure we didn't lose track of something.

**Comment by ijuma** [comment]
Thanks @ewencp .

**Comment by miguno** [comment]
> For individual packages, we should not have Depends clauses in the packages for Java because that causes problems if you want to use a non-system-provided JVM, so it should only be a build issue. If I remember correctly, only the RPMs actually specify Build-Depends. Everything else just relies on the VM being used to have the right thing installed, which should only require fixes in confluentinc/packaging.

For the record:  Only the `debian` branch in `kafka-packaging` has a Build-Depends.

```
$ git grep -i java|grep -v "^debian/patches"
debian/control.in:Build-Depends: debhelper (>= 9), java7-jdk, javahelper (>= 0.40),
debian/create_archive.sh:LIBPATH=${PREFIX}/share/java/kafka
```
